FROM debian:12

# Install dependencies and Salt Minion
RUN apt-get update && apt-get install -y curl \
    && curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io \
    && chmod +x bootstrap-salt.sh \
    && ./bootstrap-salt.sh \
    && rm -f bootstrap-salt.sh \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

CMD ["salt-minion", "-l", "debug"]
